"""initial schema — users/roles/permissions, products, transactions, settings

Revision ID: 0001
Revises:
Create Date: 2026-07-11

Hand-written (not autogenerated) to match app/models/ exactly for PostgreSQL —
see README "Migrations" section for why autogenerate wasn't used here.

Every table's primary key is a client-generated UUID (str(uuid.uuid4()) in
Python, per app/models/*.py `default=_uuid`) rather than a server-side
default, so no `server_default=gen_random_uuid()` appears below — the ORM
always supplies the id before INSERT.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- Enums (Section 6.2 roles/permissions; Epic A commission type; Epic B/F order & receivable state) ---
    commission_type_enum = postgresql.ENUM(
        "percentage", "flat", name="commission_type", create_type=True
    )
    payment_term_enum = postgresql.ENUM(
        "paid_immediately", "credit", name="payment_term", create_type=True
    )
    receivable_status_enum = postgresql.ENUM(
        "open", "closed", name="receivable_status", create_type=True
    )
    commission_type_enum.create(op.get_bind(), checkfirst=True)
    payment_term_enum.create(op.get_bind(), checkfirst=True)
    receivable_status_enum.create(op.get_bind(), checkfirst=True)

    # --- Epic E: users / roles / permissions ---
    op.create_table(
        "roles",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("name", sa.String(50), nullable=False, unique=True),
    )

    op.create_table(
        "permissions",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("code", sa.String(100), nullable=False, unique=True),
    )

    op.create_table(
        "role_permissions",
        sa.Column(
            "role_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("roles.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "permission_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("permissions.id", ondelete="CASCADE"),
            primary_key=True,
        ),
    )

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("username", sa.String(100), nullable=False, unique=True),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("role_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("roles.id"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_users_username", "users", ["username"])

    # --- Epic A: master data ---
    op.create_table(
        "channels",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("code", sa.String(20), nullable=False, unique=True),
        sa.Column("name", sa.String(50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )

    op.create_table(
        "skus",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("code", sa.String(50), nullable=False, unique=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("category", sa.String(100), nullable=False),
        sa.Column("size_variant", sa.String(50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("current_stock_qty", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("current_avg_cost", sa.Numeric(12, 4), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
        ),
    )
    op.create_index("ix_skus_code", "skus", ["code"])
    op.create_index("ix_skus_name", "skus", ["name"])

    op.create_table(
        "channel_prices",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("sku_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("skus.id"), nullable=False),
        sa.Column(
            "channel_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("channels.id"), nullable=False
        ),
        sa.Column("price", sa.Numeric(12, 2), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("effective_from", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column(
            "created_by_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("users.id"), nullable=False
        ),
    )
    op.create_index(
        "ix_channel_prices_sku_channel_current",
        "channel_prices",
        ["sku_id", "channel_id", "is_current"],
    )

    op.create_table(
        "channel_commissions",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "channel_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("channels.id"), nullable=False
        ),
        sa.Column(
            "commission_type",
            postgresql.ENUM("percentage", "flat", name="commission_type", create_type=False),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(12, 4), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("effective_from", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column(
            "created_by_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("users.id"), nullable=False
        ),
    )
    op.create_index(
        "ix_channel_commissions_channel_current", "channel_commissions", ["channel_id", "is_current"]
    )

    # --- Epic B: purchases, orders ---
    op.create_table(
        "purchases",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("vendor", sa.String(200), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column(
            "created_by_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("users.id"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "purchase_items",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "purchase_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("purchases.id"), nullable=False
        ),
        sa.Column("sku_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("skus.id"), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(12, 4), nullable=False),
        sa.Column("line_total", sa.Numeric(14, 2), nullable=False),
        sa.Column("resulting_avg_cost", sa.Numeric(12, 4), nullable=False),
    )
    op.create_index("ix_purchase_items_sku_id", "purchase_items", ["sku_id"])

    op.create_table(
        "orders",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "channel_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("channels.id"), nullable=False
        ),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column(
            "payment_term",
            postgresql.ENUM("paid_immediately", "credit", name="payment_term", create_type=False),
            nullable=True,
        ),
        sa.Column("party_name", sa.String(200), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "created_by_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("users.id"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_orders_date_channel", "orders", ["order_date", "channel_id"])

    op.create_table(
        "order_items",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("order_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("orders.id"), nullable=False),
        sa.Column("sku_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("skus.id"), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("selling_price_at_sale", sa.Numeric(12, 2), nullable=False),
        sa.Column("cost_price_at_sale", sa.Numeric(12, 4), nullable=False),
        sa.Column("commission_amount_at_sale", sa.Numeric(12, 2), nullable=False),
        sa.Column("revenue", sa.Numeric(14, 2), nullable=False),
        sa.Column("net_profit", sa.Numeric(14, 2), nullable=False),
        sa.Column("price_overridden", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_order_items_sku_id", "order_items", ["sku_id"])

    # --- Epic B (grouped with F per Implementation Plan Section 4): returns, receivables, payments ---
    op.create_table(
        "returns",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "order_item_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("order_items.id"),
            nullable=True,
        ),
        sa.Column("sku_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("skus.id"), nullable=False),
        sa.Column(
            "channel_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("channels.id"), nullable=False
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("return_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("revenue_reversed", sa.Numeric(14, 2), nullable=False),
        sa.Column("cost_reversed", sa.Numeric(14, 2), nullable=False),
        sa.Column("commission_reversed", sa.Numeric(14, 2), nullable=False),
        sa.Column("net_profit_reversed", sa.Numeric(14, 2), nullable=False),
        sa.Column(
            "created_by_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("users.id"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_returns_sku_id", "returns", ["sku_id"])

    op.create_table(
        "receivables",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "order_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("orders.id"),
            nullable=False,
            unique=True,
        ),
        sa.Column("amount_total", sa.Numeric(14, 2), nullable=False),
        sa.Column("amount_outstanding", sa.Numeric(14, 2), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("open", "closed", name="receivable_status", create_type=False),
            nullable=False,
            server_default="open",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "payments",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "receivable_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("receivables.id"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(14, 2), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column(
            "created_by_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("users.id"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    # Implementation Plan Section 8 calls this out explicitly for the outstanding-
    # amount calculation. Payment's natural FK here is receivable_id (a Receivable
    # is already 1:1 with an Order via its own unique order_id), so this index
    # serves the same "find payments for this order's balance" query path.
    op.create_index("ix_payments_receivable_id", "payments", ["receivable_id"])

    # --- Epic E: system settings (seeded in 0002) ---
    op.create_table(
        "system_settings",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("key", sa.String(100), nullable=False, unique=True),
        sa.Column("value", sa.String(500), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
        ),
        sa.Column(
            "updated_by_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("users.id"), nullable=True
        ),
    )


def downgrade() -> None:
    op.drop_table("system_settings")
    op.drop_index("ix_payments_receivable_id", table_name="payments")
    op.drop_table("payments")
    op.drop_table("receivables")
    op.drop_index("ix_returns_sku_id", table_name="returns")
    op.drop_table("returns")
    op.drop_index("ix_order_items_sku_id", table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_orders_date_channel", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_purchase_items_sku_id", table_name="purchase_items")
    op.drop_table("purchase_items")
    op.drop_table("purchases")
    op.drop_index("ix_channel_commissions_channel_current", table_name="channel_commissions")
    op.drop_table("channel_commissions")
    op.drop_index("ix_channel_prices_sku_channel_current", table_name="channel_prices")
    op.drop_table("channel_prices")
    op.drop_index("ix_skus_name", table_name="skus")
    op.drop_index("ix_skus_code", table_name="skus")
    op.drop_table("skus")
    op.drop_table("channels")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_table("users")
    op.drop_table("role_permissions")
    op.drop_table("permissions")
    op.drop_table("roles")

    postgresql.ENUM(name="receivable_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="payment_term").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="commission_type").drop(op.get_bind(), checkfirst=True)
